import React, { useState, useContext } from "react";
import { DarkThemeContext } from "../../Context/DarkThemContext";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faEnvelope } from "@fortawesome/free-solid-svg-icons";
import { faGithub } from "@fortawesome/free-brands-svg-icons";
import { faFacebook } from "@fortawesome/free-brands-svg-icons";
import { faTelegram } from "@fortawesome/free-brands-svg-icons";

const Footer = () => {
  const { isDarkTheme, setisDarkTheme } = useContext(DarkThemeContext);
  const backgroundColor = isDarkTheme ? "black" : "white";
  const borderStyle = isDarkTheme ? "1px solid #5b5b5b" : "";
  const linkStyle =
    "text-gray relative after:transition-all after:duration-500 after:scale-0 after:content-[''] after:absolute after:left-0 lg:after:top-5 after:top-[20px] after:w-full after:h-0.5 after:bg-gray after:rounded-lg hover:after:scale-100 lg:after:hover:top-5 after:hover:top-[20px] after:hover:left-0 after:hover:h-[2.5px]  after:hover:rounded-lg";
  const iconsStyle = "w-8 h-8 cursor-pointer";
  return (
    <section
      className={`w-[100%] h-60 flex items-center justify-end flex-col  ${
        isDarkTheme ? "bg-black" : "bg-gradient-to-t from-blue to-white"
      } `}
    >
      <div className="w-full px-40 flex items-center justify-center lg:justify-between m-auto ">
        <div className="hidden lg:flex text-gray text-5xl font-black">
          myBlOOOG!<span className="text-[2rem]">&#8482;</span>
        </div>
        <div className="flex items-center justify-between gap-x-6 text-gray">
          <FontAwesomeIcon icon={faEnvelope} className={iconsStyle} />
          <FontAwesomeIcon icon={faGithub} className={iconsStyle} />
          <FontAwesomeIcon icon={faFacebook} className={iconsStyle} />
          <FontAwesomeIcon icon={faTelegram} className={iconsStyle} />
        </div>
      </div>
      <div className="h-[2px] w-[calc(100%-10rem)] bg-gray my-3"></div>
      <div className="flex items-center justify-center  flex-col my-4 text-gray font-semibold">
        <p>
          This Site Generated By{" "}
          <a className={linkStyle} href="">
            ABDELAJLIL LAFKIR
          </a>
        </p>
        <p>&#9400; 2024 myBLOOOGY. All Right Reserved.</p>
      </div>
    </section>
  );
};

export default Footer;
